project:
  type: book
  output-dir: docs

book:
  title: "rOpenSci Champions Program Mentor Guidelines v2.0"
  author: "Yanina Bellini Saibene"
  date: "2024-01-05"
  chapters:
    - index.qmd
    - introduction.qmd
    - mentors-tools.qmd
    - mentorship-meetings.qmd
    - mentorship-skills.qmd
    - sources.qmd
    - feedback.qmd
