project:
  type: book
  output-dir: docs

book:
  title: "rOpenSci Champions Program Mentor Guidelines v2.0"
  author: "Yanina Bellini Saibene"
  date: "2024-01-05"
  chapters:
    - index.qmd
    - introduction.qmd
    - mentors-tools.qmd
    - mentorship-meetings.qmd
    - mentorship-skills.qmd
    - sources.qmd

babelquarto:
  languagecodes:
  - name: es
    text: "Version in es"
  - name: en
    text: "Version in en"
  mainlanguage: 'en'
  languages: ['es']
title-es: Orientaciones para mentor(a|e)s del Programa de Campeon(e|a)s de rOpenSci v2.0
description-es: ""
author-es: Yanina Bellini Saibene
lang: en
