project:
  type: book
  output-dir: docs

book:
  title: "rOpenSci Champions Program Mentor Guidelines v2.0"
  author: "Yanina Bellini Saibene"
  date: "2024-01-05"
  chapters:
    - index.qmd
    - introduction.qmd
    - part: Introduction
      part-es: Introducción
    - mentors-tools.qmd
    - part: Mentors Tools
      part-es: Herramientas
    - mentorship-meetings.qmd
    - part: Mentorship Meetings
      part-es: Reuniones de mentoría
    - mentorship-skills.qmd
    - part: Mentorship Skills
      part-es: Habilidades de mentoría
    - sources.qmd
    - part: Sources
      part-es: Fuentes

babelquarto:
  languagelinks: sidebar
  languagecodes:
  - name: es
    text: "Español"
  - name: en
    text: "English"
  mainlanguage: 'en'
  languages: ['es']
title-es: Orientaciones para mentor(a|e)s del Programa de Campeon(e|a)s de rOpenSci v2.0
description-es: ""
author-es: Yanina Bellini Saibene
lang: en
