# Introducción

## Te damos la bienvenida

Gracias por ofrecerte para ser mentor del [Programa de Campeon(a|e)s de rOpenSci](https://ropensci.org/champions/)

Desarrollamos esta guía para ayudarte a navegar por la logística del
programa y proporcionar herramientas para tu papel como *mentor* o *mentora*.

Como documento vivo que construimos en comunidad, siempre estamos muy agradecidos por
comentarios, mejoras y contribuciones.

## Descripción de funciones

Las personas mentoras desempeñarán un papel vital en el Programa
aconsejando e inspirando a tu campeón o campeona.También conectarán a sus
a sus aprendices con personas, programas y organizaciones, recomendándoles recursos,
lecturas, formación y experiencias.
También van a proveer feedback sobre el proyecto del campeón o campeona.

Trabajarás con la persona que mentorees para desarrollar su proyecto, que puede ser una
de las siguientes opciones:

- Crear un nuevo paquete;

- Pasar por el proceso de revisión con un paquete en R que ya tengan
  desarrollado;

- Servir como revisor o revisora para [el sistema de revisión por pares de software de rOpenSci.](https://ropensci.org/es/software-review/)

Mentor(e|a)s también pueden apoyar a los Campeon(e|a)s en la realización de otras actividades
entre las que se incluyen: dar una charla, escribir artículos o notas técnicas para el blog de rOpenSci y enseñar a otras personas
 de la comunidad.

## Cronología del Programa

Se espera que el compromiso de tiempo total sea de aproximadamente **2-4 horas
al mes** desde **mayo de 2025 - julio de 2025** para completar el
siguiente calendario provisional del programa.

| **Fecha**                        | **Evento**                                                                      | **Detalle**                                                                                                                                                                                                                | **Duración**                       | 
| ----------------------- | --------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------- |
| Octubre de 2023         | Seleccionar campeones                                                 | Revisa, clasifica y selecciona 1-2 proyectos revisados para mentorizarlos.                                                                                                                                      | 2 h                    | 
| noviembre de 2023       | Acto inaugural                                                        | Infórmate sobre el programa, revisa las expectativas del programa y resuelve tus dudas. Conoce a los alumnos.                                                                                                   | 1\.5 h                  | 
| enero - abril 2024      | Formación                                                             | Cómo hacer de mentor y logística en el programa.                                                                                                                                                                | 2 h                    | 
| marzo-julio 2024        | Reunión con el alumno                                                 | Proporcionar comentarios y orientación sobre el proyecto del alumno.  Ponerle en contacto con otros expertos, mentores o miembros de la comunidad. Recomendar formación y recursos para el proyecto del alumno. | 1 reunión al mes 0,5 h | 
| Mayo de 2024            | Reunión de cohortes [opcional]                                        | Los campeones presentarán su proyecto y recibirán comentarios.                                                                                                                                                  | 1\.5 h                  | 
| agosto - noviembre 2023 | Reunión con el alumno                                                 | Proporcionar comentarios y orientación sobre el proyecto del alumno.  Ponerle en contacto con otros expertos, mentores o miembros de la comunidad. Recomendar formación y recursos para el proyecto del alumno. | 1 reunión al mes 0,5 h | 
| Julio de 2024           | Reunión de cohortes [opcional]: Reflexiones sobre los proyectos       | Se invitará a los promotores a compartir con la cohorte las conclusiones de sus proyectos.                                                                                                                      | 1\.5 h                  | 
| Septiembre de 2024      | Reunión de cohortes [opcional]: Reflexiones sobre los acontecimientos | Se invitará a los promotores a compartir con la cohorte las conclusiones de sus actos.                                                                                                                          | 1\.5 h                  | 
| Octubre de 2024         | Reunión de cohortes: Reflexiones sobre el programa                    | Se invitará a los mentores a compartir las conclusiones del programa y a ayudar a definir las futuras funciones de los Campeones.                                                                               | 1\.5 h                  | 
| Noviembre de 2024       | Fin del plazo                                                         | Cerrar la cohorte y definir nuevas funciones para los Campeones y Mentores.                                                                                                                                     | 1 h                    | 

## Enlaces rápidos

### Social

[Página Web del Programa Campeones en el sitio de rOpenSci](https://ropensci.org/es/champions/) y [Sitio Web del Programa](https://champions-program.ropensci.org)
<https://ropensci.org/champions/>

Slack: ropensci.slack.com

[Mastodon](https://hachyderm.io/@rOpenSci)
<https://hachyderm.io/@rOpenSci>

[LinkedIn](https://www.linkedin.com/company/ropensci/)

[Vimeo (canal de videos)](https://vimeo.com/ropensci)

GitHub: [https://github.com/ropensci](https://github.com/ropensci)

### Código de conducta

[Código de Conducta (versión en español)](https://ropensci.org/es/código-de-conducta/)

### Contacto/Reunión con la _Community Manager_

[Calendly](https://calendly.com/yabellini-ropensci) - Reserva una reunión con Yani (puedes elegir desde 15 a 60
minutos)

Correo electrónico: [*yabellini@ropensci.org*](mailto:yabellini@ropensci.org)

# Comentarios

Contribuciones de todo tipo son bienvenidas, desde sugerencias para
mejoras, erratas y material nuevo. Por favor, ponte en contacto con
con tus ideas.


