# Habilidades de mentoría

Esta es una lista de recursos y herramientas de la formación para Mentor(a|e)s de rOpenSci.
Puedes acceder a todos los [material de la capacitación](https://ropensci-training.github.io/ropensci-mentors/) incluido las
[*diapositivas*](https://docs.google.com/presentation/d/1OQ_EpW6cgebENt-gBtG53WbgvioIy_EU9Ntym7wJocg/). También compartimos las notas colaborativas de la reunión ancladas en el canal de Slack para mentores y mentoras.

## Escucha activa

Consejos para la escucha activa:

- Suspende el juicio y escucha.

- Presta toda tu atención a quien habla (no ensayes lo que 
  vas a decir/contestar)

- Anima a la quien habla con señales verbales y no verbales.

## Preguntas efectivas

Las preguntas nos permiten

- Acceder a la información y analizarla.

- Estimular el pensamiento y la creatividad.

- Aprender mediante el debate.

Ver el modelo [*GROW (CRECE en Inglés)*](#grow-model) para ver ejemplos.

## Dar retroalimentación (feedback)

Es más fácil dar y recibir opiniones cuando ambas partes comparten
expectativas sobre lo que está y no está dentro del alcance y sobre cómo los comentarios
deben formularse los comentarios.

Consejos para dar retroalimentación:

- Intenta ser útil.

- Ve a lo concreto. Céntrate en comportamientos observables.

- Habla por ti.

- Equilibra los elogios y los comentarios críticos: es importante decirle a las personas lo que
  deben seguir haciendo, así como lo que deben cambiar.

## Modelo _GROW_

**Objetivo:** Acuerda un tema y un objetivo o una o dos metas a más largo plazo.

**Realidad:** autoevaluación, ejemplos concretos.

**Opciones:** sugerencias ofrecidas y elecciones realizadas.

**Camino a seguir:** próximos pasos.

Consejos para el modelo _GROW_:

- "Pregunta" en lugar de "habla".

- Ilustra y comprueba la comprensión.

- ¡Piensa de forma creativa!

- No necesitas ser una persona experta en la situación: estás 
  facilitando.

Ejemplos de preguntas:

META u OBJETIVOS

- ¿Qué quieres conseguir?

- ¿Qué ocurrirá cuando lo hayas conseguido?

- Los OBJETIVOS pueden ser _SMART_ (inteligentes en Inglés): Específicos, Mensurables, Alcanzables, Realistas y Temporales.

REALIDAD

- ¿Qué está ocurriendo en este momento?

- ¿Qué te impide seguir adelante?

- ¿Qué has intentado?

- ¿Qué ha pasado?

- ¿Qué has aprendido?

OPCIONES

- ¿Qué podrías hacer? ¿Qué otra cosa más podrías hacer?

- ¿Cuáles son las ventajas/desventajas de cada opción?

- ¿Quieres que te haga sugerencias?

- ¿Qué opciones te gustan más?

CAMINO A SEGUIR

- ¿Qué vas a hacer?

- ¿Cuál será el primer paso?

- ¿Cuándo exactamente vas a empezar y terminar cada paso?

- ¿Qué apoyo necesitas y de quién?


