# Mentorship Skills

This is a list of resources and tools from the Mentor training and
orientation meeting. You can access the
[*slides*](https://docs.google.com/presentation/d/1qAv8IfSMRRGbQlwOkyM7QvnYQSEvL-cUFPj72ixNgN4/edit?usp=sharing)
and the shared notes (meeting 1 and meeting 2).

## Active Listening

Tips for active listening:

- Suspend judgment and listen

- Give your full attention to the speaker (don’t rehearse what you’re
  going to say)

- Encourage the speaker with verbal and nonverbal cues

## Effective Questioning

Questions let us:

- Access & analyze information

- Stimulate thinking & creativity

- Learn through discussion

See the [*GROW*](#grow-model) model for examples.

## Giving Feedback

Feedback is easier to give and receive when both parties share
expectations about what is and isn’t in scope and about how comments
ought to be phrased.

Tips for giving feedback:

- Try to be helpful

- Be specific. Focus on observable behavior.

- Speak for yourself

- Balance praise & critical feedback: it’s important to tell people what
  they should keep doing as well as what they should change.

## GROW Model

**Goal:** Agree on a topic & objective or longer-term goals

**Reality:** self-assessment, specific examples

**Options:** suggestions offered & choices made

**Way forward:** next steps

GROW model tips:

- ‘Ask’ rather than ‘tell’

- Illustrate and check understanding

- Think creatively!

- You don’t need to be an expert in the situation - you’re acting as a
  facilitator

Sample Questions:

GOAL

- What do you want to achieve?

- What will be happening when you have succeeded?

- GOALS can be SMART (Specific, Measurable, Achievable, Realistic, Time
  bound)

REALITY

- What is happening at the moment?

- What stops you from moving on?

- What have you tried?

- What happened?

- What have you learned?

OPTIONS

- What could you do? What else?

- What are the advantages/ disadvantages of each option?

- Would you like suggestions from me?

- What options do you like the most?

WAY FORWARD

- What will you do?

- What will be the first step?

- When precisely are you going to start and finish each step?

- What support do you need and from whom?
